package seeders

import (
	"crypto/rand"
	"encoding/hex"
	"fmt"
	mathrand "math/rand"
	"strconv"
	"strings"
	"time"
)

var fakeRand = mathrand.New(mathrand.NewSource(time.Now().UnixNano()))

var fakeFirstNames = []string{"Liam", "Olivia", "Noah", "Emma", "Mason", "Sophia", "Ethan", "Mia"}
var fakeLastNames = []string{"Smith", "Johnson", "Brown", "Taylor", "Anderson", "Martin", "Walker", "Hall"}
var fakeCompanies = []string{"Bookly", "Northwind", "Acme", "Nimbus", "Atlas", "Bluepeak"}
var fakeDomains = []string{"example.com", "mail.test", "bookly.app", "forge.dev"}
var fakeSentences = []string{
	"Sample text generated by Forge.",
	"Another seed row ready for local development.",
	"Generated fixture content for testing flows.",
}

func expandFixtureRows(s YAMLSeed) ([]map[string]any, error) {
	if len(s.Rows) > 0 {
		rows := cloneRows(s.Rows)
		for i := range rows {
			if err := resolveFakeValues(rows[i]); err != nil {
				return nil, err
			}
		}
		return rows, nil
	}

	if len(s.Template) == 0 || s.Count <= 0 {
		return s.Rows, nil
	}

	rows := make([]map[string]any, 0, s.Count)
	for i := 0; i < s.Count; i++ {
		row := cloneRow(s.Template)
		if err := resolveFakeValues(row); err != nil {
			return nil, err
		}
		rows = append(rows, row)
	}
	return rows, nil
}

func resolveFakeValues(row map[string]any) error {
	for key, value := range row {
		resolved, err := resolveFakeValue(value)
		if err != nil {
			return fmt.Errorf("field %s: %w", key, err)
		}
		row[key] = resolved
	}
	return nil
}

func resolveFakeValue(value any) (any, error) {
	switch v := value.(type) {
	case string:
		return fakeValue(v)
	case map[string]any:
		cloned := cloneRow(v)
		if err := resolveFakeValues(cloned); err != nil {
			return nil, err
		}
		return cloned, nil
	case []any:
		out := make([]any, len(v))
		for i := range v {
			item, err := resolveFakeValue(v[i])
			if err != nil {
				return nil, err
			}
			out[i] = item
		}
		return out, nil
	default:
		return value, nil
	}
}

func fakeValue(input string) (any, error) {
	trimmed := strings.TrimSpace(input)
	if !strings.HasPrefix(trimmed, "fake:") {
		return input, nil
	}

	token := strings.TrimPrefix(trimmed, "fake:")
	switch {
	case token == "first_name":
		return pick(fakeFirstNames), nil
	case token == "last_name":
		return pick(fakeLastNames), nil
	case token == "full_name":
		return fmt.Sprintf("%s %s", pick(fakeFirstNames), pick(fakeLastNames)), nil
	case token == "email":
		return fmt.Sprintf("%s.%s%d@%s",
			strings.ToLower(pick(fakeFirstNames)),
			strings.ToLower(pick(fakeLastNames)),
			fakeRand.Intn(1000),
			pick(fakeDomains),
		), nil
	case token == "company":
		return pick(fakeCompanies), nil
	case token == "phone":
		return fmt.Sprintf("+1-555-%03d-%04d", fakeRand.Intn(1000), fakeRand.Intn(10000)), nil
	case token == "sentence":
		return pick(fakeSentences), nil
	case token == "uuid":
		return fakeUUID(), nil
	case token == "datetime":
		return fakeDateTime().Format("2006-01-02 15:04:05"), nil
	case token == "date":
		return fakeDateTime().Format("2006-01-02"), nil
	case token == "bool":
		return fakeRand.Intn(2) == 0, nil
	case strings.HasPrefix(token, "int:"):
		return fakeInt(token)
	default:
		return nil, fmt.Errorf("unsupported fake token %q", trimmed)
	}
}

func fakeInt(token string) (int, error) {
	parts := strings.Split(token, ":")
	if len(parts) != 3 {
		return 0, fmt.Errorf("invalid fake int token %q", token)
	}
	min, err := strconv.Atoi(parts[1])
	if err != nil {
		return 0, fmt.Errorf("invalid fake int min %q", parts[1])
	}
	max, err := strconv.Atoi(parts[2])
	if err != nil {
		return 0, fmt.Errorf("invalid fake int max %q", parts[2])
	}
	if max < min {
		return 0, fmt.Errorf("invalid fake int range %d..%d", min, max)
	}
	return min + fakeRand.Intn(max-min+1), nil
}

// fakeDateTime returns a random instant within roughly the past year.
func fakeDateTime() time.Time {
	days := fakeRand.Intn(365)
	secs := fakeRand.Intn(86400)
	return time.Now().AddDate(0, 0, -days).Add(-time.Duration(secs) * time.Second)
}

func fakeUUID() string {
	var b [16]byte
	_, _ = rand.Read(b[:])
	b[6] = (b[6] & 0x0f) | 0x40
	b[8] = (b[8] & 0x3f) | 0x80
	buf := make([]byte, 36)
	hex.Encode(buf[0:8], b[0:4])
	buf[8] = '-'
	hex.Encode(buf[9:13], b[4:6])
	buf[13] = '-'
	hex.Encode(buf[14:18], b[6:8])
	buf[18] = '-'
	hex.Encode(buf[19:23], b[8:10])
	buf[23] = '-'
	hex.Encode(buf[24:36], b[10:16])
	return string(buf)
}

func pick(values []string) string {
	return values[fakeRand.Intn(len(values))]
}

func cloneRows(rows []map[string]any) []map[string]any {
	out := make([]map[string]any, len(rows))
	for i := range rows {
		out[i] = cloneRow(rows[i])
	}
	return out
}

func cloneRow(row map[string]any) map[string]any {
	out := make(map[string]any, len(row))
	for k, v := range row {
		out[k] = v
	}
	return out
}
